version: "3"

services:
    server:
        container_name: server
        build: server/
        ports: 
            - "3000:3000"
        env_file: .env
        networks:
            - network
        depends_on: 
            - postgres
    client:
        container_name: client
        build: client/
        ports:
            - "8080:80"
        depends_on: 
            - server
    postgres:
        container_name: postgres
        image: postgres
        env_file: .env
        ports:
            - "5432:5432"
        networks:
            - network
        volumes: 
             - /vbshnsk/docker/pg:/var/lib/postgresql/data 

networks:
    network:
        driver: bridge

