version: "3"

services:
    server:
        container_name: server
        build: server/
        ports: 
            - "3000:3000"
        env_file: .env
        networks:
            - network
        depends_on: 
            - postgres
        volumes:
            - ./server:/app
    client:
        container_name: client
        build: client/
        ports:
            - "8080:8080"
        depends_on: 
            - server
        volumes:
            - ./client:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm run serve
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - "5432:5432"
        networks:
            - network
        volumes: 
            - $HOME/docker/volumes/pg-matchify:/var/lib/postgresql/data 

networks:
    network:
        driver: bridge

