insert into "Genre"(name, maingenre) values ('acid rock', 'rock'),
('acoustic', 'rock'),
('alternative rock', 'rock'),
('aor', 'rock'),
('arena rock', 'rock'),
('art rock', 'rock'),
('atmospheric black metal', 'rock'),
('avantgarde', 'rock'),
('beat', 'rock'),
('black metal', 'rock'),
('blues rock', 'rock'),
('brit pop', 'rock'),
('classic rock', 'rock'),
('coldwave', 'rock'),
('country rock', 'rock'),
('crust', 'rock'),
('death metal', 'rock'),
('deathcore', 'rock'),
('deathrock', 'rock'),
('depressive black metal', 'rock'),
('doo wop', 'rock'),
('doom metal', 'rock'),
('dream pop', 'rock'),
('emo', 'rock'),
('ethereal', 'rock'),
('experimental rock', 'rock'),
('folk metal', 'rock'),
('folk rock', 'rock'),
('funeral doom metal', 'rock'),
('funk metal', 'rock'),
('garage rock', 'rock'),
('glam', 'rock'),
('goregrind', 'rock'),
('goth rock', 'rock'),
('gothic metal', 'rock'),
('grindcore', 'rock'),
('grunge', 'rock'),
('hard rock', 'rock'),
('hardcore', 'rock'),
('heavy metal', 'rock'),
('horror rock', 'rock'),
('indie rock', 'rock'),
('industrial', 'rock'),
('krautrock', 'rock'),
('lo-fi', 'rock'),
('lounge', 'rock'),
('math rock', 'rock'),
('melodic death metal', 'rock'),
('melodic hardcore', 'rock'),
('metalcore', 'rock'),
('mod', 'rock'),
('ndw', 'rock'),
('neofolk', 'rock'),
('new wave', 'rock'),
('no wave', 'rock'),
('noise', 'rock'),
('noisecore', 'rock'),
('nu metal', 'rock'),
('oi', 'rock'),
('parody', 'rock'),
('pop punk', 'rock'),
('pop rock', 'rock'),
('pornogrind', 'rock'),
('post rock', 'rock'),
('post-hardcore', 'rock'),
('post-metal', 'rock'),
('post-punk', 'rock'),
('power metal', 'rock'),
('power pop', 'rock'),
('power violence', 'rock'),
('prog rock', 'rock'),
('progressive metal', 'rock'),
('psychedelic rock', 'rock'),
('psychobilly', 'rock'),
('pub rock', 'rock'),
('punk', 'rock'),
('rock & roll', 'rock'),
('rock opera', 'rock'),
('rockabilly', 'rock'),
('shoegaze', 'rock'),
('ska', 'rock'),
('skiffle', 'rock'),
('sludge metal', 'rock'),
('soft rock', 'rock'),
('southern rock', 'rock'),
('space rock', 'rock'),
('speed metal', 'rock'),
('stoner rock', 'rock'),
('surf', 'rock'),
('swamp pop', 'rock'),
('symphonic rock', 'rock'),
('technical death metal', 'rock'),
('thrash', 'rock'),
('twist', 'rock'),
('viking metal', 'rock'),
('yé-yé', 'rock'),
('rock', 'rock') on conflict do nothing ;

insert into "Genre"(name, maingenre) values ('boogie woogie', 'blues'),
('chicago blues', 'blues'),
('country blues', 'blues'),
('delta blues', 'blues'),
('east coast blues', 'blues'),
('electric blues', 'blues'),
('harmonica blues', 'blues'),
('jump blues', 'blues'),
('louisiana blues', 'blues'),
('memphis blues', 'blues'),
('modern electric blues', 'blues'),
('piano blues', 'blues'),
('piedmont blues', 'blues'),
('rhythm & blues', 'blues'),
('texas blues', 'blues'),
('blues', 'blues') on conflict do nothing ;

insert into "Genre"(name, maingenre) values ('baroque', 'classical'),
('choral', 'classical'),
('classical', 'classical'),
('contemporary', 'classical'),
('early', 'classical'),
('impressionist', 'classical'),
('medieval', 'classical'),
('modern', 'classical'),
('neo-classical', 'classical'),
('neo-romantic', 'classical'),
('opera', 'classical'),
('operetta', 'classical'),
('oratorio', 'classical'),
('post-modern', 'classical'),
('renaissance', 'classical'),
('romantic', 'classical'),
('serial', 'classical'),
('twelve-tone', 'classical'),
('zarzuela', 'classical') on conflict do nothing ;

insert into "Genre"(name, maingenre) values ('abstract', 'electronic'),
('acid', 'electronic'),
('acid house', 'electronic'),
('acid jazz', 'electronic'),
('ambient', 'electronic'),
('ballroom', 'electronic'),
('baltimore club', 'electronic'),
('bassline', 'electronic'),
('beatdown', 'electronic'),
('berlin-school', 'electronic'),
('big beat', 'electronic'),
('breakbeat', 'electronic'),
('breakcore', 'electronic'),
('breaks', 'electronic'),
('broken beat', 'electronic'),
('chillwave', 'electronic'),
('chiptune', 'electronic'),
('dance-pop', 'electronic'),
('dark ambient', 'electronic'),
('darkwave', 'electronic'),
('deep house', 'electronic'),
('deep techno', 'electronic'),
('disco', 'electronic'),
('disco polo', 'electronic'),
('donk', 'electronic'),
('doomcore', 'electronic'),
('downtempo', 'electronic'),
('drone', 'electronic'),
('drum n bass', 'electronic'),
('dub', 'electronic'),
('dub techno', 'electronic'),
('dubstep', 'electronic'),
('dungeon synth', 'electronic'),
('ebm', 'electronic'),
('electro', 'electronic'),
('electro house', 'electronic'),
('electroclash', 'electronic'),
('euro house', 'electronic'),
('euro-disco', 'electronic'),
('eurobeat', 'electronic'),
('eurodance', 'electronic'),
('experimental', 'electronic'),
('freestyle', 'electronic'),
('funkot', 'electronic'),
('future jazz', 'electronic'),
('gabber', 'electronic'),
('garage house', 'electronic'),
('ghetto', 'electronic'),
('ghetto house', 'electronic'),
('ghettotech', 'electronic'),
('glitch', 'electronic'),
('goa trance', 'electronic'),
('grime', 'electronic'),
('hands up', 'electronic'),
('happy hardcore', 'electronic'),
('hard beat', 'electronic'),
('hard house', 'electronic'),
('hard techno', 'electronic'),
('hard trance', 'electronic'),
('hardcore', 'electronic'),
('hardstyle', 'electronic'),
('harsh noise wall', 'electronic'),
('hi nrg', 'electronic'),
('hip-house', 'electronic'),
('house', 'electronic'),
('idm', 'electronic'),
('illbient', 'electronic'),
('industrial', 'electronic'),
('italo house', 'electronic'),
('italo-disco', 'electronic'),
('italodance', 'electronic'),
('j-core', 'electronic'),
('jazzdance', 'electronic'),
('juke', 'electronic'),
('jumpstyle', 'electronic'),
('jungle', 'electronic'),
('latin', 'electronic'),
('leftfield', 'electronic'),
('lento violento', 'electronic'),
('makina', 'electronic'),
('minimal', 'electronic'),
('minimal techno', 'electronic'),
('modern classical', 'electronic'),
('musique concrète', 'electronic'),
('neo trance', 'electronic'),
('neofolk', 'electronic'),
('nerdcore techno', 'electronic'),
('new age', 'electronic'),
('new beat', 'electronic'),
('new wave', 'electronic'),
('noise', 'electronic'),
('nu-disco', 'electronic'),
('power electronics', 'electronic'),
('progressive breaks', 'electronic'),
('progressive house', 'electronic'),
('progressive trance', 'electronic'),
('psy-trance', 'electronic'),
('rhythmic noise', 'electronic'),
('schranz', 'electronic'),
('skweee', 'electronic'),
('sound collage', 'electronic'),
('speed garage', 'electronic'),
('speedcore', 'electronic'),
('synth-pop', 'electronic'),
('synthwave', 'electronic'),
('tech house', 'electronic'),
('tech trance', 'electronic'),
('techno', 'electronic'),
('trance', 'electronic'),
('tribal', 'electronic'),
('tribal house', 'electronic'),
('trip hop', 'electronic'),
('tropical house', 'electronic'),
('uk funky', 'electronic'),
('uk garage', 'electronic'),
('vaporwave', 'electronic'),
('witch house', 'electronic'),
('electronic', 'electronic')  on conflict do nothing ;

insert into "Genre"(name, maingenre) values ('alternative country', 'country'),
('cowpunk', 'country'),
('americana', 'country'),
('australian country', 'country'),
('bakersfield sound', 'country'),
('bluegrass', 'country'),
('progressive bluegrass', 'country'),
('cajun', 'country'),
('cajun fiddle', 'country'),
('christian country', 'country'),
('classic country', 'country'),
('close harmony', 'country'),
('country blues', 'country'),
('country pop', 'country'),
('country rap', 'country'),
('country rock', 'country'),
('cowboy', 'country'),
('cowboy pop', 'country'),
('dansband', 'country'),
('hokum', 'country'),
('honky tonk', 'country'),
('música sertaneja', 'country'),
('nashville sound', 'country'),
('neotraditional country', 'country'),
('outlaw country', 'country'),
('progressive country', 'country'),
('red dirt', 'country'),
('rockabilly', 'country'),
('hellbilly', 'country'),
('psychobilly', 'country'),
('texas country', 'country'),
('traditional country', 'country'),
('truck-driving country', 'country'),
('western swing', 'country'),
('zydeco', 'country'),
('country', 'country')  on conflict do nothing;

insert into "Genre"(name, maingenre) values ('ambient', 'electronic'),
('ambient dub', 'electronic'),
('dark ambient', 'electronic'),
('dungeon synth', 'electronic'),
('drone music', 'electronic'),
('illbient', 'electronic'),
('isolationism', 'electronic'),
('psybient', 'electronic'),
('space music', 'electronic'),
('asian underground', 'electronic'),
('breakbeat', 'electronic'),
('acid breaks', 'electronic'),
('baltimore club', 'electronic'),
('big beat', 'electronic'),
('broken beat', 'electronic'),
('florida breaks', 'electronic'),
('nu-funk', 'electronic'),
('miami bass', 'electronic'),
('jersey club', 'electronic'),
('nu skool breaks', 'electronic'),
('disco', 'electronic'),
('afro / cosmic disco', 'electronic'),
('disco polo', 'electronic'),
('euro disco', 'electronic'),
('italo disco', 'electronic'),
('nu-disco', 'electronic'),
('space disco', 'electronic'),
('downtempo', 'electronic'),
('acid jazz', 'electronic'),
('chill-out', 'electronic'),
('new-age music', 'electronic'),
('space music', 'electronic'),
('trip hop', 'electronic'),
('drum and bass', 'electronic'),
('liquid funk', 'electronic'),
('neurofunk', 'electronic'),
('neurohop', 'electronic'),
('jump-up', 'electronic'),
('darkstep', 'electronic'),
('drumstep', 'electronic'),
('funkstep', 'electronic'),
('hardstep', 'electronic'),
('sambass', 'electronic'),
('techstep', 'electronic'),
('dub', 'electronic'),
('ambient dub', 'electronic'),
('dancehall', 'electronic'),
('dub poetry', 'electronic'),
('dub reggae', 'electronic'),
('dub techno', 'electronic'),
('dubstep', 'electronic'),
('dubtronica', 'electronic'),
('electro music', 'electronic'),
('freestyle music', 'electronic'),
('electroacoustic music', 'electronic'),
('acousmatic music', 'electronic'),
('musique concrète', 'electronic'),
('electronic dance music', 'electronic'),
('electronic rock', 'electronic'),
('alternative dance', 'electronic'),
('indietronica', 'electronic'),
('coldwave', 'electronic'),
('dance-punk', 'electronic'),
('dark wave', 'electronic'),
('neoclassical dark wave', 'electronic'),
('electroclash', 'electronic'),
('electronicore', 'electronic'),
('electropunk', 'electronic'),
('ethereal wave', 'electronic'),
('krautrock', 'electronic'),
('minimal wave', 'electronic'),
('new rave', 'electronic'),
('nu-gaze', 'electronic'),
('space rock', 'electronic'),
('synthpop', 'electronic'),
('electronica', 'electronic'),
('berlin school', 'electronic'),
('dubtronica', 'electronic'),
('ethnic electronica', 'electronic'),
('folktronica', 'electronic'),
('funktronica', 'electronic'),
('laptronica', 'electronic'),
('livetronica', 'electronic'),
('electro swing', 'electronic'),
('hardcore', 'electronic'),
('gabba', 'electronic'),
('4-beat', 'electronic'),
('breakbeat hardcore', 'electronic'),
('bouncy techno', 'electronic'),
('breakcore', 'electronic'),
('digital hardcore', 'electronic'),
('darkcore', 'electronic'),
('happy hardcore', 'electronic'),
('mákina', 'electronic'),
('speedcore', 'electronic'),
('uk hardcore', 'electronic'),
('doomcore', 'electronic'),
('hardstyle', 'electronic'),
('dubstyle', 'electronic'),
('jumpstyle', 'electronic'),
('lento violento', 'electronic'),
('hardbass', 'electronic'),
('hi-nrg', 'electronic'),
('eurobeat', 'electronic'),
('eurodance', 'electronic'),
('bubblegum dance', 'electronic'),
('italo dance', 'electronic'),
('house music', 'electronic'),
('acid house', 'electronic'),
('ambient house', 'electronic'),
('balearic beat', 'electronic'),
('chicago house', 'electronic'),
('deep house', 'electronic'),
('future house', 'electronic'),
('tropical house', 'electronic'),
('diva house', 'electronic'),
('electro house', 'electronic'),
('big room house', 'electronic'),
('complextro', 'electronic'),
('fidget house', 'electronic'),
('dutch house', 'electronic'),
('moombahton', 'electronic'),
('moombahcore', 'electronic'),
('french house', 'electronic'),
('funky house', 'electronic'),
('garage house', 'electronic'),
('ghetto house', 'electronic'),
('ghettotech', 'electronic'),
('hardbag', 'electronic'),
('hard house', 'electronic'),
('hard dance', 'electronic'),
('hard nrg', 'electronic'),
('hip house', 'electronic'),
('italo house', 'electronic'),
('jazz house', 'electronic'),
('kidandali', 'electronic'),
('kwaito', 'electronic'),
('latin house', 'electronic'),
('microhouse/minimal house', 'electronic'),
('new beat', 'electronic'),
('outsider house', 'electronic'),
('progressive house', 'electronic'),
('rara tech', 'electronic'),
('tech house', 'electronic'),
('tribal house', 'electronic'),
('trival', 'electronic'),
('witch house', 'electronic'),
('industrial music', 'electronic'),
('aggrotech', 'electronic'),
('cybergrind', 'electronic'),
('electro-industrial', 'electronic'),
('dark electro', 'electronic'),
('electronic body music', 'electronic'),
('futurepop', 'electronic'),
('industrial metal', 'electronic'),
('industrial rock', 'electronic'),
('japanoise', 'electronic'),
('martial industrial', 'electronic'),
('neue deutsche härte', 'electronic'),
('power electronics', 'electronic'),
('death industrial', 'electronic'),
('power noise', 'electronic'),
('idm', 'electronic'),
('glitch', 'electronic'),
('glitch hop', 'electronic'),
('wonky', 'electronic'),
('jungle', 'electronic'),
('darkcore jungle', 'electronic'),
('raggacore', 'electronic'),
('post-disco', 'electronic'),
('boogie', 'electronic'),
('electropop', 'electronic'),
('chillwave', 'electronic'),
('vaporwave', 'electronic'),
('dance-pop', 'electronic'),
('dance-rock', 'electronic'),
('slime punk', 'electronic'),
('synthwave', 'electronic'),
('sovietwave', 'electronic'),
('techno', 'electronic'),
('acid techno', 'electronic'),
('detroit techno', 'electronic'),
('dub techno', 'electronic'),
('free tekno', 'electronic'),
('minimal techno', 'electronic'),
('nortec', 'electronic'),
('tecno brega', 'electronic'),
('techdombe', 'electronic'),
('trance music', 'electronic'),
('acid trance', 'electronic'),
('balearic trance', 'electronic'),
('dream trance', 'electronic'),
('euro-trance', 'electronic'),
('hard trance', 'electronic'),
('nitzhonot', 'electronic'),
('psychedelic trance', 'electronic'),
('full on', 'electronic'),
('suomisaundi', 'electronic'),
('goa trance', 'electronic'),
('progressive trance', 'electronic'),
('tech trance', 'electronic'),
('uplifting trance', 'electronic'),
('vocal trance', 'electronic'),
('uk garage', 'electronic'),
('2-step garage', 'electronic'),
('dubstep', 'electronic'),
('brostep', 'electronic'),
('chillstep', 'electronic'),
('drumstep', 'electronic'),
('reggaestep', 'electronic'),
('trapstep', 'electronic'),
('metalstep', 'electronic'),
('vomitstep', 'electronic'),
('breakstep', 'electronic'),
('future garage', 'electronic'),
('grime', 'electronic'),
('grindie', 'electronic'),
('speed garage', 'electronic'),
('bassline/4x4 garage', 'electronic'),
('uk funky', 'electronic'),
('vaporwave', 'electronic'),
('video game music', 'electronic'),
('chiptune', 'electronic'),
('bitpop', 'electronic'),
('game boy music', 'electronic'),
('shiny', 'electronic'),
('skweee', 'electronic'),
('nintendocore', 'electronic'),
('splatune', 'electronic') on conflict do nothing;

insert into "Genre"(name, maingenre) values ('alternative hip hop', 'hiphop'),
('avant-garde hip hop', 'hiphop'),
('breakbeat', 'hiphop'),
('boom bap', 'hiphop'),
('cat rap', 'hiphop'),
('chap hop', 'hiphop'),
('chopped and screwed', 'hiphop'),
('chopper', 'hiphop'),
('christian hip hop', 'hiphop'),
('comedy hip hop', 'hiphop'),
('contemporary r&b', 'hiphop'),
('conscious hip hop', 'hiphop'),
('country-rap', 'hiphop'),
('crunk', 'hiphop'),
('crunkcore', 'hiphop'),
('cloud rap', 'hiphop'),
('drill', 'hiphop'),
('electro hop', 'hiphop'),
('emo hip hop', 'hiphop'),
('experimental hip hop', 'hiphop'),
('freestyle rap', 'hiphop'),
('g-funk', 'hiphop'),
('gangsta rap', 'hiphop'),
('persian rap', 'hiphop'),
('ghetto house', 'hiphop'),
('ghettotech', 'hiphop'),
('glitch hop', 'hiphop'),
('hardcore hip hop', 'hiphop'),
('hip hop soul', 'hiphop'),
('hip house', 'hiphop'),
('horrorcore', 'hiphop'),
('hyphy', 'hiphop'),
('industrial hip hop', 'hiphop'),
('instrumental hip hop', 'hiphop'),
('jazz rap', 'hiphop'),
('jersey club', 'hiphop'),
('latin trap', 'hiphop'),
('lo-fi hip hop', 'hiphop'),
('low bap', 'hiphop'),
('miami bass', 'hiphop'),
('neurohop', 'hiphop'),
('new jack swing', 'hiphop'),
('political hip hop', 'hiphop'),
('pop-rap', 'hiphop'),
('porno rap', 'hiphop'),
('ragga hip hop', 'hiphop'),
('rap opera', 'hiphop'),
('rap rock', 'hiphop'),
('rap metal', 'hiphop'),
('snap music', 'hiphop'),
('mumble rap', 'hiphop'),
('stronda music', 'hiphop'),
('trap', 'hiphop'),
('trip hop', 'hiphop'),
('illbient', 'hiphop'),
('trvxrap', 'hiphop'),
('turntablism', 'hiphop'),
('underground hip hop', 'hiphop'),
('urban pasifika', 'hiphop'),
('albanian hip hop', 'hiphop'),
('austrian hip hop', 'hiphop'),
('belgian hip hop', 'hiphop'),
('bosnian hip hop', 'hiphop'),
('british hip hop', 'hiphop'),
('bulgarian hip hop', 'hiphop'),
('croatian hip hop', 'hiphop'),
('czech hip hop', 'hiphop'),
('danish hip hop', 'hiphop'),
('dutch hip hop', 'hiphop'),
('finnish hip hop', 'hiphop'),
('french hip hop', 'hiphop'),
('german hip hop', 'hiphop'),
('greek hip hop', 'hiphop'),
('hungarian hip hop', 'hiphop'),
('icelandic hip hop', 'hiphop'),
('irish hip hop', 'hiphop'),
('italian hip hop', 'hiphop'),
('macedonian hip hop', 'hiphop'),
('norwegian hip hop', 'hiphop'),
('polish hip hop', 'hiphop'),
('portuguese hip hop', 'hiphop'),
('romanian hip hop', 'hiphop'),
('romany hip hop', 'hiphop'),
('russian hip hop', 'hiphop'),
('scottish hip hop', 'hiphop'),
('serbian hip hop', 'hiphop'),
('slovak hip hop', 'hiphop'),
('slovenian hip hop', 'hiphop'),
('spanish hip hop', 'hiphop'),
('swedish hip hop', 'hiphop'),
('swiss hip hop', 'hiphop'),
('ukrainian hip hop', 'hiphop'),
('bangladeshi hip hop', 'hiphop'),
('burmese hip hop', 'hiphop'),
('chinese hip hop', 'hiphop'),
('filipino hip hop', 'hiphop'),
('hong kong hip hop', 'hiphop'),
('indian hip hop', 'hiphop'),
('desi hip hop', 'hiphop'),
('indonesian hip hop', 'hiphop'),
('japanese hip hop', 'hiphop'),
('korean hip hop', 'hiphop'),
('malaysian hip hop', 'hiphop'),
('nepalese hip hop', 'hiphop'),
('pakistani hip hop', 'hiphop'),
('thai hip hop', 'hiphop'),
('taiwanese hip hop', 'hiphop'),
('algerian hip hop', 'hiphop'),
('gambian hip hop', 'hiphop'),
('ghanaian hip hop', 'hiphop'),
('ivorian hip hop', 'hiphop'),
('kenyan hip hop', 'hiphop'),
('moroccan hip hop', 'hiphop'),
('nigerian hip hop', 'hiphop'),
('nigerien hip hop', 'hiphop'),
('senegalese hip hop', 'hiphop'),
('south african hip hop', 'hiphop'),
('tanzanian hip hop', 'hiphop'),
('togolese hip hop', 'hiphop'),
('tunisian hip hop', 'hiphop'),
('zambian hip hop', 'hiphop'),
('zimbabwean hip hop', 'hiphop'),
('arabic hip hop', 'hiphop'),
('egyptian hip hop', 'hiphop'),
('iranian hip hop', 'hiphop'),
('israeli hip hop', 'hiphop'),
('kurdish hip hop', 'hiphop'),
('lebanese hip hop', 'hiphop'),
('palestinian hip hop', 'hiphop'),
('saudi hip hop', 'hiphop'),
('turkish hip hop', 'hiphop'),
('yemeni hip hop', 'hiphop'),
('canadian hip hop', 'hiphop'),
('cuban hip hop', 'hiphop'),
('dominican hip hop', 'hiphop'),
('haitian hip hop', 'hiphop'),
('mexican hip hop', 'hiphop'),
('salvadoran hip hop', 'hiphop'),
('australian hip hop', 'hiphop'),
('new zealand hip hop', 'hiphop'),
('brazilian hip hop', 'hiphop'),
('colombian hip hop', 'hiphop'),
('uruguayan hip hop', 'hiphop'),
('hip-hop', 'hiphop'),
('hip hop', 'hiphop') on conflict do nothing;

insert into "Genre"(name, maingenre) values ('brazilian', 'latin'),
('axé', 'latin'),
('brazilian rock', 'latin'),
('brega', 'latin'),
('tecnobrega', 'latin'),
('choro', 'latin'),
('forró', 'latin'),
('frevo', 'latin'),
('funk carioca', 'latin'),
('lambada', 'latin'),
('zouk-lambada', 'latin'),
('maracatu', 'latin'),
('música popular brasileira', 'latin'),
('tropicalia', 'latin'),
('música sertaneja', 'latin'),
('new mexico music', 'latin'),
('samba', 'latin'),
('pagode', 'latin'),
('samba rock', 'latin'),
('boogaloo', 'latin'),
('latin christian', 'latin'),
('latin jazz', 'latin'),
('afro-cuban jazz', 'latin'),
('bossa nova', 'latin'),
('latin pop', 'latin'),
('latin ballad', 'latin'),
('latin swing', 'latin'),
('latin rock', 'latin'),
('latin alternative', 'latin'),
('rock en español', 'latin'),
('reggaeton', 'latin'),
('latin trap', 'latin'),
('regional mexican', 'latin'),
('banda', 'latin'),
('norteño', 'latin'),
('flamenco', 'latin'),
('tango', 'latin'),
('bullerengue', 'latin'),
('fado', 'latin'),
('grupera', 'latin'),
('huayno', 'latin'),
('mariachi', 'latin'),
('ranchera', 'latin'),
('mexican son', 'latin'),
('música criolla', 'latin'),
('nueva canción', 'latin'),
('tropical', 'latin'),
('bachata', 'latin'),
('bolero', 'latin'),
('criolla', 'latin'),
('cumbia', 'latin'),
('chicha', 'latin'),
('porro', 'latin'),
('guajira', 'latin'),
('mambo', 'latin'),
('merengue', 'latin'),
('rumba', 'latin'),
('salsa', 'latin'),
('salsa romántica', 'latin'),
('son', 'latin'),
('tejano', 'latin'),
('timba', 'latin'),
('tropipop', 'latin'),
('vallenato', 'latin'),
('latin', 'latin') on conflict do nothing;

insert into "Genre"(name, maingenre) values ('adult contemporary', 'pop'),
('arab pop', 'pop'),
('baroque pop', 'pop'),
('brill building', 'pop'),
('britpop', 'pop'),
('bubblegum pop', 'pop'),
('canción', 'pop'),
('canzone', 'pop'),
('chalga', 'pop'),
('chanson', 'pop'),
('christian pop', 'pop'),
('classical crossover', 'pop'),
('country pop', 'pop'),
('c-pop', 'pop'),
('hokkien pop', 'pop'),
('mandopop', 'pop'),
('cringe pop', 'pop'),
('dance-pop', 'pop'),
('disco polo', 'pop'),
('electropop', 'pop'),
('europop', 'pop'),
('austropop', 'pop'),
('eurobeat', 'pop'),
('french pop', 'pop'),
('italo dance', 'pop'),
('italo disco', 'pop'),
('laïkó', 'pop'),
('latin pop', 'pop'),
('nederpop', 'pop'),
('russian pop', 'pop'),
('fado', 'pop'),
('folk pop', 'pop'),
('iranian pop', 'pop'),
('indie pop', 'pop'),
('twee pop', 'pop'),
('j-pop', 'pop'),
('jangle pop', 'pop'),
('k-pop', 'pop'),
('korean hip hop', 'pop'),
('korean rock', 'pop'),
('t''ong guitar', 'pop'),
('trot', 'pop'),
('latin ballad', 'pop'),
('louisiana swamp pop', 'pop'),
('mexican pop', 'pop'),
('new romantic', 'pop'),
('operatic pop', 'pop'),
('pop rap', 'pop'),
('pop rock', 'pop'),
('power pop', 'pop'),
('soft rock', 'pop'),
('pop punk', 'pop'),
('neon pop', 'pop'),
('emo pop', 'pop'),
('pop soul', 'pop'),
('progressive pop', 'pop'),
('psychedelic pop', 'pop'),
('rebetiko', 'pop'),
('schlager', 'pop'),
('sophisti-pop', 'pop'),
('space age pop', 'pop'),
('sunshine pop', 'pop'),
('surf pop', 'pop'),
('synthpop', 'pop'),
('teen pop', 'pop'),
('traditional pop music', 'pop'),
('turkish pop', 'pop'),
('vispop', 'pop'),
('wonky pop', 'pop'),
('worldbeat', 'pop'),
('adult contemporary music', 'pop'),
('akishibu-kei', 'pop'),
('arabic pop music', 'pop'),
('art pop', 'pop'),
('austropop', 'pop'),
('avant-pop', 'pop'),
('avant-garde pop', 'pop'),
('balkan ballad', 'pop'),
('beat music', 'pop'),
('boy band', 'pop'),
('brill building', 'pop'),
('bubblegum pop', 'pop'),
('čalgija', 'pop'),
('california sound', 'pop'),
('cantopop', 'pop'),
('chalga', 'pop'),
('chillwave', 'pop'),
('christian pop music', 'pop'),
('country pop', 'pop'),
('coupé-décalé', 'pop'),
('cowboy pop', 'pop'),
('cringe pop', 'pop'),
('crunkcore', 'pop'),
('dance-pop', 'pop'),
('doo-wop', 'pop'),
('easy listening', 'pop'),
('electropop', 'pop'),
('estrada', 'pop'),
('eurodance', 'pop'),
('europop', 'pop'),
('experimental pop', 'pop'),
('folk-pop', 'pop'),
('global k-pop', 'pop'),
('group sounds', 'pop'),
('hokkien pop', 'pop'),
('hong kong english pop', 'pop'),
('hypnagogic pop', 'pop'),
('indian pop', 'pop'),
('italo dance', 'pop'),
('kayōkyoku', 'pop'),
('latin pop', 'pop'),
('lounge music', 'pop'),
('mandopop', 'pop'),
('manele', 'pop'),
('mexican pop', 'pop'),
('nashville sound', 'pop'),
('nederbeat', 'pop'),
('nordik beat', 'pop'),
('operatic pop', 'pop'),
('orchestral pop', 'pop'),
('pop black metal', 'pop'),
('pop punk', 'pop'),
('pop rap', 'pop'),
('pop rock', 'pop'),
('popcorn', 'pop'),
('progressive pop', 'pop'),
('psychedelic music', 'pop'),
('psychedelic pop', 'pop'),
('quiet storm', 'pop'),
('russian pop', 'pop'),
('sentimental ballad', 'pop'),
('shibuya-kei', 'pop'),
('shidaiqu', 'pop'),
('skiladiko', 'pop'),
('smooth jazz', 'pop'),
('sophisti-pop', 'pop'),
('space age pop', 'pop'),
('sundanese pop', 'pop'),
('sunshine pop', 'pop'),
('swamp pop', 'pop'),
('symphonic pop', 'pop'),
('synth-pop', 'pop'),
('tallava', 'pop'),
('teen pop', 'pop'),
('thai pop music', 'pop'),
('traditional pop', 'pop'),
('tropical rock', 'pop'),
('tropipop', 'pop'),
('turbo-folk', 'pop'),
('vispop', 'pop'),
('wong shadow', 'pop'),
('wonky pop', 'pop'),
('zhongguo feng', 'pop'),
('pop', 'pop') on conflict do nothing;

insert into "Genre"(name, maingenre) values ('contemporary r&b', 'rnb'),
('disco', 'rnb'),
('funk', 'rnb'),
('deep funk', 'rnb'),
('minneapolis sound', 'rnb'),
('freestyle music', 'rnb'),
('go-go', 'rnb'),
('hip hop soul', 'rnb'),
('p-funk', 'rnb'),
('post-disco', 'rnb'),
('boogie', 'rnb'),
('pbr&b', 'rnb'),
('gospel music', 'rnb'),
('new jack swing', 'rnb'),
('rhythm and blues', 'rnb'),
('soul', 'rnb'),
('blue-eyed soul', 'rnb'),
('hip hop soul', 'rnb'),
('northern soul', 'rnb'),
('neo soul', 'rnb'),
('southern soul', 'rnb'),
('rnb', 'rnb'),
('contemporary rnb', 'rnb'),
('alternative rnb', 'rnb'),
('r&b', 'rnb') on conflict do nothing;

insert into "Genre"(name, maingenre) values ('acid rock', 'rock'),
('afro-punk', 'rock'),
('alternative metal', 'rock'),
('alternative rock', 'rock'),
('americana music', 'rock'),
('anarcho-punk', 'rock'),
('anatolian rock', 'rock'),
('art punk', 'rock'),
('art rock', 'rock'),
('avant-garde metal', 'rock'),
('baroque pop', 'rock'),
('baggy', 'rock'),
('bandana thrash', 'rock'),
('beach music', 'rock'),
('beat music', 'rock'),
('bent edge', 'rock'),
('big beat', 'rock'),
('biker metal', 'rock'),
('bisrock', 'rock'),
('blackgaze', 'rock'),
('blackened death metal', 'rock'),
('black metal', 'rock'),
('blues rock', 'rock'),
('boogie rock', 'rock'),
('brazilian thrash metal', 'rock'),
('british folk rock', 'rock'),
('britpop', 'rock'),
('britpop revival', 'rock'),
('canterbury sound', 'rock'),
('cello rock', 'rock'),
('cello metal', 'rock'),
('celtic punk', 'rock'),
('celtic metal', 'rock'),
('celtic rock', 'rock'),
('chicano rock', 'rock'),
('christian alternative rock', 'rock'),
('christian hardcore', 'rock'),
('christian metal', 'rock'),
('christian punk', 'rock'),
('christian rock', 'rock'),
('cock rock', 'rock'),
('coldwave', 'rock'),
('college rock', 'rock'),
('comedy rock', 'rock'),
('country rock', 'rock'),
('cowpunk', 'rock'),
('crossover thrash', 'rock'),
('crunkcore', 'rock'),
('crust punk', 'rock'),
('dance-punk', 'rock'),
('dance-rock', 'rock'),
('dark cabaret', 'rock'),
('darkwave', 'rock'),
('d-beat', 'rock'),
('death ''n'' roll', 'rock'),
('deathcore', 'rock'),
('death-doom', 'rock'),
('deathgrind', 'rock'),
('death metal', 'rock'),
('deathrock', 'rock'),
('digital hardcore', 'rock'),
('djent', 'rock'),
('doom metal', 'rock'),
('dream pop', 'rock'),
('drone metal', 'rock'),
('electroclash', 'rock'),
('electropunk', 'rock'),
('electronicore', 'rock'),
('electronic rock', 'rock'),
('emo', 'rock'),
('emo pop', 'rock'),
('emo revival', 'rock'),
('ethereal wave', 'rock'),
('experimental rock', 'rock'),
('extreme metal', 'rock'),
('flamenco rock', 'rock'),
('folk metal', 'rock'),
('folk punk', 'rock'),
('folk rock', 'rock'),
('funk metal', 'rock'),
('funk rock', 'rock'),
('garage punk', 'rock'),
('garage rock', 'rock'),
('geek rock', 'rock'),
('glam metal', 'rock'),
('glam punk', 'rock'),
('glam rock', 'rock'),
('goregrind', 'rock'),
('gothabilly', 'rock'),
('gothic metal', 'rock'),
('gothic rock', 'rock'),
('grebo', 'rock'),
('grindcore', 'rock'),
('grindie', 'rock'),
('groove metal', 'rock'),
('group sounds', 'rock'),
('grunge', 'rock'),
('gypsy punk', 'rock'),
('hard rock', 'rock'),
('hardcore punk', 'rock'),
('heartland rock', 'rock'),
('heavy hardcore', 'rock'),
('heavy metal', 'rock'),
('horror punk', 'rock'),
('indie folk', 'rock'),
('indie pop', 'rock'),
('indie rock', 'rock'),
('indietronica', 'rock'),
('indorock', 'rock'),
('industrial metal', 'rock'),
('industrial rock', 'rock'),
('instrumental rock', 'rock'),
('italian occult psychedelia', 'rock'),
('jazz rock', 'rock'),
('jangle pop', 'rock'),
('jersey shore sound', 'rock'),
('krautrock', 'rock'),
('kawaii metal', 'rock'),
('latin alternative', 'rock'),
('latin metal', 'rock'),
('latin rock', 'rock'),
('madchester', 'rock'),
('manila sound', 'rock'),
('mathcore', 'rock'),
('math rock', 'rock'),
('medieval folk rock', 'rock'),
('medieval metal', 'rock'),
('melodic death metal', 'rock'),
('melodic hardcore', 'rock'),
('melodic metalcore', 'rock'),
('metalcore', 'rock'),
('mod revival', 'rock'),
('nardcore', 'rock'),
('neue deutsche härte', 'rock'),
('neue deutsche todeskunst', 'rock'),
('neue deutsche welle', 'rock'),
('neoclassical dark wave', 'rock'),
('neoclassical metal', 'rock'),
('neon pop', 'rock'),
('neo-progressive rock', 'rock'),
('neo-psychedelia', 'rock'),
('new rave', 'rock'),
('new wave', 'rock'),
('new wave of new wave', 'rock'),
('new weird america', 'rock'),
('nintendocore', 'rock'),
('noise pop', 'rock'),
('noise rock', 'rock'),
('no wave', 'rock'),
('nu gaze', 'rock'),
('nu metal', 'rock'),
('nu metalcore', 'rock'),
('occult rock', 'rock'),
('oi!', 'rock'),
('ostrock', 'rock'),
('outlaw country', 'rock'),
('pagan metal', 'rock'),
('pagan rock', 'rock'),
('paisley underground', 'rock'),
('peace punk', 'rock'),
('pinoy rock', 'rock'),
('pirate metal', 'rock'),
('pop punk', 'rock'),
('pop rock', 'rock'),
('pornogrind', 'rock'),
('post-britpop', 'rock'),
('post-grunge', 'rock'),
('post-hardcore', 'rock'),
('post-metal', 'rock'),
('post-punk', 'rock'),
('post-punk revival', 'rock'),
('post-rock', 'rock'),
('power pop', 'rock'),
('power metal', 'rock'),
('powerviolence', 'rock'),
('progressive metal', 'rock'),
('progressive metalcore', 'rock'),
('progressive rock', 'rock'),
('protopunk', 'rock'),
('psychedelic funk', 'rock'),
('psychedelic pop', 'rock'),
('psychedelic rock', 'rock'),
('psychobilly', 'rock'),
('pub rock', 'rock'),
('punk blues', 'rock'),
('punk jazz', 'rock'),
('punk rap', 'rock'),
('punk pathetique', 'rock'),
('punk rock', 'rock'),
('queercore', 'rock'),
('raga rock', 'rock'),
('rapcore', 'rock'),
('rap metal', 'rock'),
('rap rock', 'rock'),
('reggae rock', 'rock'),
('red dirt', 'rock'),
('rock and roll', 'rock'),
('rockabilly', 'rock'),
('roots rock', 'rock'),
('sadcore', 'rock'),
('samba rock', 'rock'),
('screamo', 'rock'),
('shoegazing', 'rock'),
('shock rock', 'rock'),
('ska punk', 'rock'),
('skate punk', 'rock'),
('slowcore', 'rock'),
('sludge metal', 'rock'),
('soft rock', 'rock'),
('southern rock', 'rock'),
('space rock', 'rock'),
('speed metal', 'rock'),
('straight edge', 'rock'),
('stoner rock', 'rock'),
('street punk', 'rock'),
('sufi rock', 'rock'),
('sunshine pop', 'rock'),
('surf music', 'rock'),
('swamp pop', 'rock'),
('swedish death metal', 'rock'),
('symphonic black metal', 'rock'),
('symphonic metal', 'rock'),
('synthpop', 'rock'),
('taqwacore', 'rock'),
('technical death metal', 'rock'),
('thrashcore', 'rock'),
('thrash metal', 'rock'),
('trall punk', 'rock'),
('trap metal', 'rock'),
('trønder rock', 'rock'),
('tropical rock', 'rock'),
('tulsa sound', 'rock'),
('2 tone', 'rock'),
('viking metal', 'rock'),
('viking rock', 'rock'),
('visual kei', 'rock'),
('wagnerian rock', 'rock'),
('wizard rock', 'rock'),
('midwest emo', 'rock') on conflict do nothing;

insert into "Genre"(name, maingenre) values ('acid jazz', 'jazz'),
('afro-cuban jazz', 'jazz'),
('alt-jazz', 'jazz'),
('asian american jazz', 'jazz'),
('avant-garde jazz', 'jazz'),
('bebop', 'jazz'),
('boogie-woogie', 'jazz'),
('bossa nova', 'jazz'),
('british dance band', 'jazz'),
('cape jazz', 'jazz'),
('chamber jazz', 'jazz'),
('continental jazz', 'jazz'),
('cool jazz', 'jazz'),
('crossover jazz', 'jazz'),
('dixieland', 'jazz'),
('ethno jazz', 'jazz'),
('european free jazz', 'jazz'),
('free funk', 'jazz'),
('free improvisation', 'jazz'),
('free jazz', 'jazz'),
('gypsy jazz', 'jazz'),
('hard bop', 'jazz'),
('jazz blues', 'jazz'),
('jazz-funk', 'jazz'),
('jazz fusion', 'jazz'),
('jazz rap', 'jazz'),
('jazz rock', 'jazz'),
('kansas city blues', 'jazz'),
('kansas city jazz', 'jazz'),
('latin jazz', 'jazz'),
('livetronica', 'jazz'),
('m-base', 'jazz'),
('mainstream jazz', 'jazz'),
('modal jazz', 'jazz'),
('neo-bop jazz', 'jazz'),
('neo-swing', 'jazz'),
('novelty ragtime', 'jazz'),
('nu jazz', 'jazz'),
('orchestral jazz', 'jazz'),
('post-bop', 'jazz'),
('punk jazz', 'jazz'),
('ragtime', 'jazz'),
('shibuya-kei', 'jazz'),
('ska jazz', 'jazz'),
('smooth jazz', 'jazz'),
('soul jazz', 'jazz'),
('stride jazz', 'jazz'),
('straight-ahead jazz', 'jazz'),
('swing', 'jazz'),
('third stream', 'jazz'),
('trad jazz', 'jazz'),
('vocal jazz', 'jazz'),
('west coast jazz', 'jazz'),
('jazz', 'jazz') on conflict do nothing;

insert into "Genre"(name, maingenre) values ('american folk revival', 'folk'),
('americana', 'folk'),
('anti-folk', 'folk'),
('british folk revival', 'folk'),
('celtic music', 'folk'),
('chalga', 'folk'),
('contemporary folk', 'folk'),
('corrido', 'folk'),
('filk music', 'folk'),
('folk rock', 'folk'),
('celtic rock', 'folk'),
('folktronica', 'folk'),
('freak folk', 'folk'),
('indie folk', 'folk'),
('industrial folk', 'folk'),
('neofolk', 'folk'),
('mariachi', 'folk'),
('ranchera', 'folk'),
('progressive folk', 'folk'),
('protest song', 'folk'),
('psychedelic folk', 'folk'),
('singer-songwriter', 'folk'),
('skiffle', 'folk'),
('sung poetry', 'folk'),
('western', 'folk'),
('red dirt', 'folk'),
('new mexico', 'folk'),
('texas country', 'folk'),
('tejano', 'folk'),
('folk', 'folk') on conflict do nothing;

select distinct maingenre from "Genre";